spring.application.name=springBootLearner
#logging.level.root=DEBUG

spring.datasource.username=arju
spring.datasource.password=password1
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.url=jdbc:mysql://ecommerce-db.cvo60ieq8g72.ap-south-1.rds.amazonaws.com:3306/ecommerce_db
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect